### ISSUE TITLE
[FEATURE] Option to custom/remove the last `resetStyles`

### ISSUE THREAD

**Issue by hieulw** [arl/gitmux#121]
**Is your feature request related to a problem? Please describe.**
This sounds a bit odd but I'm using gitmux to display git status in wezterm status bar because there's no git status snippets for wezterm that I found in internet. I used to use gitmux with tmux for a long time, now I want to use wezterm instead and migrate gradually to it. Everything seems ok but the last `resetStyles` there's no way of removing it in config file right now.
https://github.com/arl/gitmux/blob/main/tmux/formater.go#L213

**Describe the solution you'd like**
have an Option to whether show or not the last `resetStyles`.

**Describe alternatives you've considered**
Wezterm's config is using lua so I can just using git in sub process and get the git status values but I think gitmux would be lots more performance also the fact that it almost out-of-the-box option.

**Additional context**
<img width="585" alt="image" src="https://github.com/user-attachments/assets/d6936a1e-13e9-4eb1-917b-071431134b52">

```yaml
# gitmux.conf
tmux:
  styles:
    clear: ""
    state: ""
    branch: ""
    remote: ""
    divergence: ""
    staged: ""
    conflict: ""
    modified: ""
    untracked: ""
    stashed: ""
    insertions: ""
    deletions: ""
    clean: ""
```
