### ISSUE TITLE
[BUG] Gitmux adds block in Catppuccin theme

### ISSUE THREAD

**Issue by UncleKalle** [arl/gitmux#123]
**Describe the bug**
A block is added after gitmux module output in status bar.

**Expected behavior**
The block should not appear at all

![Image](https://github.com/user-attachments/assets/dda2ebc5-936c-4bd3-83f8-35cf77264299)

Hello everyone, similar problem to issue 105, though the fixes mentioned there didn't help. From what I've gathered so far, adding characters or whitespaces as strings in the layout-section of gitmux.conf, the background is set to the "clear" color code in styles-section. So in this regard, everything works as expected.

i **have** to set the #[default] flag in tmux.conf however, so that following modules aren't affected by the color styles of gitmux.

`set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_file}"
set -ag status-right "#{E:@catppuccin_status_gitmux}#[default]"
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
`
My theory on this: The "block" has the same color as the status bar. All other modules integrate well in the scheme. Putting gitmux to the very end of the status bar still results in a block. Could there possibly be an output of un-stialized (whitespaces)-characters, after the main output from gitmux appears?

My version of gitmux is a self compiled one for latest build (two days or so ago)
tmux is version 3.4

**Comment by arl** [comment]
Can you provide your gitmux.conf please?

**Comment by UncleKalle** [comment]
```
tmux:
    # The symbols section defines the symbols printed before specific elements
    # of Git status displayed in tmux status string.
    symbols:
        # current branch name.
        branch: "⎇ "
        # Git SHA1 hash (in 'detached' state).
        hashprefix: ":"
        # 'ahead count' when local and remote branch diverged.
        ahead: ↑·
        # 'behind count' when local and remote branch diverged.
        behind: ↓·
        # count of files in the staging area.
        staged: "● "
        # count of files in conflicts.
        conflict: "✖ "
        # count of modified files.
        modified: "✚ "
        # count of untracked files.
        untracked: "… "
        # count of stash entries.
        stashed: "⚑ "
        # count of inserted lines (stats section).
        insertions: Σ
        # count of deleted lines (stats section).
        deletions: Δ
        # Shown when the working tree is clean.
        clean: ✔

    # Styles are tmux format strings used to specify text colors and attributes
    # of Git status elements. See the STYLES section of tmux man page.
    # https://man7.org/linux/man-pages/man1/tmux.1.html#STYLES.
    styles:
        clear: '#[fg=#{@thm_fg}]'
        state: '#[fg=#{@thm_red},bold]'
        branch: '#[fg=#{@thm_fg},bold]'
        remote: '#[fg=#{@thm_teal}]'
        divergence: '#[fg=#{@thm_fg}]'
        staged: '#[fg=#{@thm_green},bold]'
        conflict: '#[fg=#{@thm_red},bold]'
        modified: '#[fg=#{@thm_yellow},bold]'
        untracked: '#[fg=#{@thm_mauve},bold]'
        stashed: '#[fg=#{@thm_blue},bold]'
        clean: '#[fg=#{@thm_rosewater},bold]'
        insertions: '#[fg=#{@thm_green}]'
        deletions: '#[fg=#{@thm_red}]'

    # The layout section defines what components gitmux shows and the order in
    # which they appear on tmux status bar.
    #
    # Allowed components:
    #  - branch:            local branch name. Examples: `⎇ main`, `⎇ :345e7a0` or `[rebase]`
    #  - remote-branch:     remote branch name, for example: `origin/main`.
    #  - divergence:        divergence between local and remote branch, if any. Example: `↓·2↑·1`
    #  - remote:            alias for `remote-branch` followed by `divergence`, for example: `origin/main ↓·2↑·1`
    #  - flags:             symbols representing the working tree state, for example `✚ 1 ⚑ 1 … 2`
    #  - stats:             insertions/deletions (lines), for example`Σ56 Δ21`
    #  - some string `foo`: any other character of string is directly shown, for example `foo` or `|`
    layout: [branch, remote-branch, divergence, " - ", flags]

    # Additional configuration options.
    options:
        # Maximum displayed length for local and remote branch names.
        branch_max_len: 0
        # Trim left, right or from the center of the branch (`right`, `left` or `center`).
        branch_trim: right
        # Character indicating whether and where a branch was truncated.
        ellipsis: …
        # Hides the clean flag
        hide_clean: true 
        # Swaps order of behind & ahead upstream counts - "↓·1↑·1" -> "↑·1↓·1".
        swap_divergence: false
        # Add a space between behind & ahead upstream counts.
        divergence_space: true 
```
The style section is a copy/paste from catppuccin after I initially changed the lines by hand, in order to overwrite possible mistakes I made.
hide_clean and divergance_space were changed in my attempts to fix the issue
