### ISSUE TITLE
Layout cannot be changed

### ISSUE THREAD

**Issue by oberprah** [arl/gitmux#22]
## Expected Behavior

I have the following `gitmux.config`, where I removed the branch-symbol and added a custom layout. With the custom layout I would remove the remote-branch.

```
tmux:
  symbols:
    branch: ''
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: ●
    conflict: '✖ '
    modified: '✚ '
    untracked: …
    stashed: '⚑ '
    clean: ✔
  styles:
    state: '#[fg=red,bold]'
    branch: '#[fg=white,bold]'
    remote: '#[fg=cyan]'
    staged: '#[fg=green,bold]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=red,bold]'
    untracked: '#[fg=magenta,bold]'
    stashed: '#[fg=cyan,bold]'
    clean: '#[fg=green,bold]'
  layouts: [branch, '  ', flags]
```

## Actual Behavior

If I call the following command `$ gitmux -cfg gitmux.conf` I get this output:

`#[fg=default]#[fg=default]#[fg=white,bold]#[fg=default]master#[fg=default]..#[fg=cyan]origin/master#[fg=default]#[fg=default] - #[fg=magenta,bold]…1%`

The branch-symbol is removed, but the layout didn't change. Where do I have to put the layout-config to change the layout?

## Specifications

  - OS: macOS
  - gitmux version: `0.4.1`
  - tmux version: `tmux 3.0a`
