### ISSUE TITLE
Local Branch text does not take formatting

### ISSUE THREAD

**Issue by mbazdell** [arl/gitmux#32]
## Expected Behavior
Setting Branch style should affect branch text

## Actual Behavior
Only affects symbol

![image](https://user-images.githubusercontent.com/5973940/89241601-65bb3100-d5cd-11ea-8903-c6a61d220d3b.png)

## Steps to Reproduce the Problem
```
tmux:
  symbols:
    branch: ' '
    hashprefix: ':'
    ahead: ↑·
    behind: ↓·
    staged: ' '
    conflict: ' '
    modified: '➕ '
    untracked: '… '
    stashed: ' '
    clean: 
  styles:
    state: '#[fg=red]'
    branch: '#[fg=white]'
    remote: '#[fg=cyan]'
    staged: '#[fg=green]'
    conflict: '#[fg=red]'
    modified: '#[fg=red]'
    untracked: '#[fg=magenta,bold]'
    stashed: '#[fg=cyan,bold]'
    clean: '#[fg=green,bold]'
  layout: [' ', branch, .., remote-branch, divergence, ' - ', flags, ' |']
  options:
    branch_max_len: 0
```
## Specifications
  - OS: Fedora 30
  - gitmux version: 0.7.0
  - tmux version: 2.9a
