### ISSUE TITLE
[BUG] Staged changes to be committed added using "git add -p" are not shown

### ISSUE THREAD

**Issue by iusmac** [arl/gitmux#61]
**Describe the bug**
Gitmux ignores staged files that are not staged at the same time. I have been experienced this behavior for quite a while in all of my projects, and I have always doubted if this is a bug or normal behavior since no one has reported it...

**To Reproduce**
1. Make a multiline changes to a file
2. Add a hunk using `git add -p <file>`
3. Check using `git status` that the `<file>` is staged and not staged at the
   same time as shown below:
<details>
  <summary>Demo</summary>

![Screenshot from 2022-02-21 10-59-46](https://user-images.githubusercontent.com/28353279/154939596-279c5d66-6d5f-4d88-80a3-1de851b2ec26.png)
</details>

**Expected behavior**
I expect gitmux to show the counters for a staged file, for a modified file and for an untracked file as in the screenshot:
<details>
  <summary>Demo</summary>

![Screenshot from 2022-02-21 10-59-46](https://user-images.githubusercontent.com/28353279/154940042-6919eabb-8f7b-480c-a2a6-fb377611b322.png)
</details>

**Environment:**
 - gitmux version: 0.7.6
 - tmux version: tmux 3.3-rc
 - OS: Ubuntu 21.10
 - shell: bash 5.1.8(1)-release
<details>
  <summary>gitmux config:</summary>

```
tmux:
  symbols:
    branch: '⎇  '
    hashprefix: '# '
    ahead: '↑ '
    behind: '↓ '
    staged: '+ '
    conflict: 'X '
    modified: '~ '
    untracked: '? '
    stashed: '⚑  '
    clean: 'OK'
  styles:
    state: '#[fg=colour1]'
    branch: '#[fg=colour8]'
    remote: ' #[fg=colour6]'
    staged: '#[fg=colour2]'
    conflict: '#[fg=colour1]'
    modified: '#[fg=colour11]'
    untracked: '#[fg=colour8]'
    stashed: '#[fg=colour6]'
    clean: '#[fg=colour2]'
  layout: [branch, remote, ' ', flags]

```
</details>

**My investigation:**
I took a look at the code and executed inside my project directory the same command with the same arguments used in:
https://github.com/arl/gitstatus/blob/3b1abc4b71ca8cf7e6b6d05f4b35a9b75715013c/status.go#L72
```go
err := runAndParse(ctx, &st.Porcelain, "git", "status", "--porcelain", "--branch", "-z")
```

For 1 modified and 1 untracked file the output was:
`## 11...origin/11 M entrypoint.sh?? README.md`

After using `git add -p` I got 1 staged, 1 modified and 1 untracked file and the output was:
`## 11...origin/11MM entrypoint.sh?? README.md`

The output is different, so it can be distinguished by the parser / interpreter.
